const {abi, bytecode} = require('./build/ExeDAO')
const fs = require('fs')
fs.writeFileSync('./abi.json', JSON.stringify({abi}))
fs.writeFileSync('./bytecode.json', JSON.stringify({bytecode}))
console.log(`Bytecode Size: ${((bytecode.length / 2 - 1)/1024).toFixed(2)}kb`)