import text from '../colors/text';
import {
  fontFamily,
  fontWeightExtraLight,
  fontWeightLight,
  fontWeightRegular,
  fontWeightBold,
  fontSize,
} from './settings';

import pxToRem from './utils/pxToRem';

const createTypography = () => ({
  useNextVariants: true,
  fontSize,
  fontFamily,
  fontWeightExtraLight,
  fontWeightLight,
  fontWeightRegular,
  fontWeightMedium: fontWeightBold,
  h1: {
    color: text.primary,
    fontWeight: fontWeightExtraLight,
    fontStyle: 'normal',
    fontSize: pxToRem(104.8),
    lineHeight: 'normal',
    letterSpacing: '-1.5px',
    textTransform: 'none',
  },
  h2: {
    color: text.primary,
    fontWeight: fontWeightExtraLight,
    fontStyle: 'normal',
    fontSize: pxToRem(65.5),
    lineHeight: 'normal',
    letterSpacing: '-0.5px',
    textTransform: 'none',
  },
  h3: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(52.1),
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textTransform: 'none',
  },
  h4: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(36.9),
    lineHeight: 'normal',
    letterSpacing: '0.3px',
    textTransform: 'none',
  },
  h5: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(26),
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textTransform: 'none',
  },
  h6: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(21.7),
    lineHeight: 'normal',
    letterSpacing: '0.3px',
    textTransform: 'none',
  },
  subtitle1: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(17.4),
    lineHeight: '1.38',
    letterSpacing: '0.2px',
    textTransform: 'none',
  },
  subtitle2: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(15.2),
    lineHeight: '1.58',
    letterSpacing: '0.1px',
    textTransform: 'none',
  },
  body1: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(17.4),
    lineHeight: '1.61',
    letterSpacing: '0.5px',
    textTransform: 'none',
  },
  body2: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(15.2),
    lineHeight: '1.32',
    letterSpacing: '0.3px',
    textTransform: 'none',
  },
  button: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(15.2),
    lineHeight: '1.05',
    letterSpacing: '1.3px',
    textTransform: 'uppercase',
  },
  caption: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(13),
    lineHeight: '1.23',
    letterSpacing: '0.4px',
    textTransform: 'none',
  },
  overline: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(13),
    lineHeight: '1.23',
    letterSpacing: '2px',
    textTransform: 'uppercase',
  },
});

export default createTypography;
